feature: livedivulgator bot
aHub-Tech/Live-Divulgador pull request #32
Opened 2021-11-04 00:33 UTC by vcwild

## O que foi feito?

- Criados handlers da rotina de criação de tweets do bot
- Implementada rotina principal de divulgar livestreams via tweets
- Implementada a possibilidade de criar plugins no livedivulgador
- Módulo base do livedivulgador foi realocado de src/bot para live_divulgator
- Criados testes para os handlers e as funções mais críticas do bot
- Projeto empacotado via setuptools
- Criado CLI do projeto, chamado `divulgator`
- Criado comando para executar a rotina principal do bot `divulgator run`

## O que precisa ser feito?

- Aumentar cobertura de testes
- Criar documentação de como executar o bot
- Conteinerizar o projeto atualizado

Closes #8 #13

2021-11-04 20:08 UTC, ttiagojm approved these changes

2021-11-04 22:35 UTC, DevRadhy requested changes

2021-11-04 22:35 UTC, DevRadhy commented on src/bot/handlers/verify_online_streamers.py
> +            breakpoint()
Abrir issue para continuar a feature e falar sobre o andamento

2021-11-04 22:35 UTC, DevRadhy commented on src/bot/live_divulgator.py
> +    def run():
Abrir issue para deixar documentado o que foi falado sobre cron jobs.

2021-11-04 22:35 UTC, DevRadhy commented on src/main.py
> +    logger.warning("Starting Live Divulgator bot")
Esse log pode se encaixar na categoria `info`

2021-11-04 22:35 UTC, DevRadhy commented on src/bot/handlers/post_tweet.py
> +    cache: dict = {
Abrir issue para ver a possibilidade de usar um banco de dados para cache, como um `redis` (já discutido por call)

2021-11-04 22:35 UTC, DevRadhy commented on src/bot/handlers/fetch_streamer_ids.py
> +from src.bot.service.streamers_service import StreamersService
A `src` havia sido removida?

2021-11-04 22:35 UTC, DevRadhy commented on src/bot/handlers/post_tweet.py
> +from src.bot.twitter.client import ClientKeys, TweetMetadata, TwitterClient
A mesma situação do comentário acima (a `src` havia sido removida?)

2021-11-04 22:35 UTC, DevRadhy commented on src/bot/handlers/verify_online_streamers.py
> +from src.bot.twitch.client import TwitchClient
A mesma situação do comentário acima (a `src` havia sido removida?)

2021-11-04 22:35 UTC, DevRadhy commented on src/bot/service/streamers_service.py
> +from src.bot.database.entities.streamer import Streamer
A mesma situação do comentário acima (a `src` havia sido removida?)

2021-11-04 22:35 UTC, DevRadhy commented on src/bot/twitch/client.py
> +from src.bot.twitch.handlers import handle_response
A mesma situação do comentário acima (a `src` havia sido removida?)

2021-11-04 22:35 UTC, DevRadhy commented on src/bot/twitch/handlers.py
> +from src.bot.twitch.exceptions import (InsufficientPermissions,
A mesma situação do comentário acima (a `src` havia sido removida?)

2021-11-04 22:35 UTC, DevRadhy commented on src/bot/twitter/client.py
> +from src.bot.twitter.message import Message
A mesma situação do comentário acima (a `src` havia sido removida?)

2021-11-04 22:35 UTC, DevRadhy commented on src/bot/twitter/generics.py
> +from src.bot.twitter.message import Message
A mesma situação do comentário acima (a `src` havia sido removida?)

2021-11-04 22:35 UTC, DevRadhy commented on src/main.py
> +from src.bot.live_divulgator import LiveDivulgator
A mesma situação do comentário acima (a `src` havia sido removida?)

2021-11-04 22:35 UTC, DevRadhy commented on src/main.py
> +from src.bot.plugins.twitter import TwitterPlugin
A mesma situação do comentário acima (a `src` havia sido removida?)

2021-11-04 22:35 UTC, DevRadhy commented on src/bot/plugins/plugin.py
>  class Plugin(ABC):
Abrir issue para discutir andamento da feature.

2021-11-04 22:35 UTC, DevRadhy commented on src/bot/live_divulgator.py
> +from src.bot.bases import Bot
A mesma situação de alguns comentários acima (a `src` havia sido removida?)

2021-11-04 22:35 UTC, DevRadhy commented on test/bot/test_bot.py
> +from src.bot.plugins.twitter import TwitterPlugin
A mesma situação do comentário acima (a `src` havia sido removida?)

2021-11-04 23:36 UTC, chrisemke approved these changes
I don't see any changes that haven't been requested yet.

2021-11-05 00:30 UTC, vcwild commented on src/bot/handlers/verify_online_streamers.py
> +            breakpoint()
nao existe isso no codigo

2021-11-05 00:31 UTC, vcwild commented on src/bot/live_divulgator.py
> +    def run():
virá no próximo PR

2021-11-05 00:31 UTC, vcwild commented on src/main.py
> +    logger.warning("Starting Live Divulgator bot")
já foi alterado em outro PR

2021-11-05 00:31 UTC, vcwild commented on src/bot/handlers/fetch_streamer_ids.py
> +from src.bot.service.streamers_service import StreamersService
sim

2021-11-05 00:32 UTC, vcwild commented on src/main.py
> +from src.bot.live_divulgator import LiveDivulgator
provavelmente vc está visualizando um commit antigo

2021-11-05 00:32 UTC, vcwild commented on src/main.py
> +from src.bot.plugins.twitter import TwitterPlugin
ver anteriores

2021-11-05 00:32 UTC, vcwild commented on src/bot/live_divulgator.py
> +from src.bot.bases import Bot
ver anteriores

2021-11-05 00:32 UTC, vcwild commented on test/bot/test_bot.py
> +from src.bot.plugins.twitter import TwitterPlugin
ver anteriores

2021-11-05 00:33 UTC, vcwild commented on src/bot/handlers/post_tweet.py
> +    cache: dict = {
por enquanto o único banco é mariadb, o resto é em memória

2021-11-05 00:33 UTC, vcwild commented on src/bot/handlers/post_tweet.py
> +from src.bot.twitter.client import ClientKeys, TweetMetadata, TwitterClient
já foi resolvido

2021-11-05 00:34 UTC, vcwild commented on src/bot/service/streamers_service.py
> +from src.bot.database.entities.streamer import Streamer
já foi resolvido

2021-11-05 00:34 UTC, vcwild commented on src/bot/twitch/handlers.py
> +from src.bot.twitch.exceptions import (InsufficientPermissions,
já foi resolvido

2021-11-05 00:34 UTC, vcwild commented on src/bot/twitter/client.py
> +from src.bot.twitter.message import Message
já foi resolvido

2021-11-05 00:34 UTC, vcwild commented on src/bot/twitter/generics.py
> +from src.bot.twitter.message import Message
já foi resolvido

2021-11-05 21:35 UTC, merged